SwanContents/swancontents/filemanager/proj_url_checker.py
=> Urls support

templates/page.html
=> Remove reference to Jira from the footer

.github/workflows/swan-ci-ca.yml, HdfsBrowser/.bumpversion.cfg, SwanHelp/.bumpversion.cfg
required fixes for bump2version
=> added v prefix only for tag and commit message

.github/workflows/swan-ci-ca.yml, SwanContents/.bumpversion.cfg
Improvements according to issue #60 
closes #60
=> Improvements for pipeline

SwanOauthRenew/README.md, SwanOauthRenew/pyproject.toml, SwanOauthRenew/setup.py, SwanOauthRenew/swanoauthrenew/__init__.py, SwanOauthRenew/swanoauthrenew/_version.py, SwanOauthRenew/swanoauthrenew/swanoauthrenew.py
=> New OauthRenew extension

.github/workflows/swan-ci-ca.yml
Fixed repository for the right one :D
=> fixed repo parameter to the right one: swan-cern/systemuser-image

SwanContents/swancontents/filemanager/swanfilemanager.py, SwanContents/swancontents/js/notebooklist.js
Hi guys,
This is required for our the JupyterLab extensions,
this allows to know when I am inside of project, but I changed the way I am sending the information,
type in the json is changed from project to directory and a new tag is created "is_project".
This is because the integration SwanContents into the Jupyterlab FileBrowser should be done in this way.
https://discourse.jupyter.org/t/custom-project-extension/6598/3
Omar.
=> implemented is_project to support jupyterlab

SwanContents/swancontents/filemanager/fileio.py, SwanContents/swancontents/filemanager/handlers.py, SwanContents/swancontents/filemanager/proj_url_checker.py, SwanContents/swancontents/filemanager/swanfilemanager.py, SwanContents/swancontents/js/notebooklist.js, SwanNotebookViewer/README.md, SwanNotebookViewer/setup.py, SwanNotebookViewer/swannotebookviewer/notebookviewer.py, SwanOauthRenew/README.md, SwanOauthRenew/swanoauthrenew/swanoauthrenew.py
Sorry for grouping but this way it's quicker to me.
This PR:
* closes #20 
* closes #100 
* fixes #101 
* fixes #102
It also does small fixes to be easier to deploy locally and (temporarily) fixes a problem created by #92 
The fixes to SwanShare will probably come with another PR.
=> Fixes for Contents, NotebookViewer and OauthRenew

SwanShare/src/api.js, SwanShare/swanshare/__init__.py, SwanShare/swanshare/serverextension.py
=> SwanShare: authenticate with CERNBox via oauth tokens

HdfsBrowser/nbextension/yarn.lock, HdfsBrowser/yarn.lock, SparkConnector/nbextension/yarn.lock, SparkConnector/yarn.lock, SparkMonitor/nbextension/yarn.lock, SwanHelp/nbextension/yarn.lock, SwanHelp/package-lock.json, SwanHelp/yarn.lock, SwanIntro/package-lock.json, SwanIntro/yarn.lock, SwanNotifications/package-lock.json, SwanNotifications/yarn.lock, SwanShare/yarn.lock
- Cherry picked all the depend-bots suggestions for npm package security updates.
=> Update dependencies of extensions

HdfsBrowser/.bumpversion.cfg, HdfsBrowser/hdfsbrowser/_version.py, HdfsBrowser/nbextension/package.json, HdfsBrowser/package.json
Update to rebuild with updated CI pipeline.
=> Update HDFS Browser

SparkConnector/.bumpversion.cfg, SparkConnector/nbextension/package.json, SparkConnector/package.json, SparkConnector/sparkconnector/_version.py
- Changes to fetch hadoop tokens from an external service on demand.
=> SparkConnector v2.2.0

SwanDask/README.md, SwanDask/setup.py, SwanDask/swandask/__init__.py, SwanDask/swandask/app.py
- increase timeout to cope with slow cvmfs loading of dependencies
- prevent errors with html response
- remove direct dask-lasbextension dependency
=> Dask wrapper improvements

SwanDask/swandask/app.py
The dashboard server listens on the same address as the scheduler.
In SWAN, the scheduler needs to listen on the Docker network
address so that it receives connections from the workers (via
container-host port forwarding). Therefore, the dashboard server
also listens on that address.
This commits makes the Dask dashboard handler configure Jupyter
server proxy with a whitelist that contains the Docker network
address of the container, so that Jupyter server proxy allows to
proxy the dashboard that listens on that address.
=> Fix 403 errors when dashboard is queried

SparkConnector/nbextension/src/extension.js
Minor improvements to the Spark connector messages in the UI
=> Minor changes to the Spark connector messages.

SparkConnector/nbextension/src/extension.js
This fixes the connector message regarding the WebUI, reverting the change in #290
=> Fix connector message, followup of #290

HdfsBrowser/MANIFEST.in, HdfsBrowser/pyproject.toml, HdfsBrowser/setup.py, SparkConnector/MANIFEST.in, SparkConnector/pyproject.toml, SparkConnector/setup.py
=> Fix compilation of SparkConnector and HdfsBrowser

SwanShare/jupyter_server_config.d/swanshare.json, SwanShare/pyproject.toml, SwanShare/setup.py, SwanShare/swanshare/__init__.py, SwanShare/swanshare/serverextension.py
Closes [SWAN-125](https://its.cern.ch/jira/browse/SWAN-125)
=> Fix SwanShare

SwanOauthRenew/jupyter_server_config.d/swanoauthrenew.json, SwanOauthRenew/setup.py, SwanOauthRenew/swanoauthrenew/__init__.py, SwanOauthRenew/swanoauthrenew/swanoauthrenew.py
And make the extension compatible with jupyter server
=> swanoauthrenew: automatic installation

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh, SwanCustomEnvironments/swancustomenvironments/serverextension.py, SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
These are some changes on how the extension approaches the arguments, including:
A new repo_type arguments comes from the frontend and is made for making the segregation on how the repostiory is treated and manipulated (can be either eos or git)
Verification on the structure of the repository is now done the extension, instead of the spawner, with the help of repo_type
On UI, distance between buttons and output box is now a bit bigger
Minor changes on comments and code details
=> Changes on custom environments

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh, SwanCustomEnvironments/swancustomenvironments/serverextension.py, SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
Fix for error when calling extension (`/customenvironments`)
EventSource does not allow to pass headers. For that reason, a `fetch` promise is used. Its approach is different, however it has the same effect for this manner and no impact from the user's experience.
A dedidacted function for errors was added.
API code was adapted to reply accordingly.
---
Specify HOME to be users home instead of EOS for performance optimization when creating environment (including mamba)
=> swancustomenvironments: Fixes and optimizations

SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
Fix method for removing last element from list
=> swancustomenvironments: Fix chunked_lines method

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh
Also exits the script when git clone process fails
=> swancustomenvironments: Change error messages

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh, SwanCustomEnvironments/swancustomenvironments/scripts/builders/mamba.sh, SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh
Install requirements at the same time as the remaining requirements for better performance
=> swancustomenvs: Fixes on installation of ipykernel

SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
Countdown is no longer needed, after meeting with Philip
=> swancustomenvironments: Remove countdown

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh, SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh, SwanCustomEnvironments/swancustomenvironments/serverextension.py, SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
When NXCals flag is specified, installs sparkconnector, sparkmonitor and py4j for accpy environments
=> swancustomenvironments: New option for NXCals

SparkConnector/setup.py, SparkConnector/sparkconnector/configuration.py
This reverts commit f1f89d5a2be514731cbcf232063790c5d7b396c5.
=> Revert "sparkconnector: Preserve the default value of extraJavaOptions"

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh, SwanCustomEnvironments/swancustomenvironments/scripts/builders/mamba.sh, SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh, SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh, SwanCustomEnvironments/swancustomenvironments/serverextension.py
Insert a new function for checking the logs produced so far and stop the process when there are errors detected.
=> swancustomenvironments: Stop execution after error installing requirements

SparkConnector/setup.py
Remove `bs4` and  `jupyterlab` and add  `requests` dependency
=> sparkconnector: Update dependencies

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh, SwanCustomEnvironments/swancustomenvironments/serverextension.py, SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
With these changes, the extension is able to deal with multiple simultaneous requests, broadcasting its messages to all of them in real time. This is useful in order to avoid that a request gets blocked waiting for the first request to finish.
It also removes the "environment already created" blocking statement and modal
=> Swan on tn multitabs

SwanCustomEnvironments/swancustomenvironments/serverextension.py
With these changes, the extension is able to deal with errors when creating the environment in multiple simultaneous requests, sharing the same status with all tabs.
=> swancustomenvironments: Multitab error handling

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh, SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
Remove deprecated env_name definition and fix `_log` function calls, and general simplification of frontend code and its logic.
=> Swan on tn local

SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html
Automatically scroll to the `output-box` height
=> Fixes from Diogo suggestions

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh
This configuration ensures the jupyter kernel uses the python in the environment under the hood and not the conda one This way, when user does `!pip install` in ATS it actually works. For more information, consult SWAN-416.
=> swancustomenvironments: Configure PATH variable in kernel.json
