.github/workflows/swan-ci-ca.yml

This is to change the version of the extension in systemuser-image.
The secret WORKFLOW_ACCESS_TOKEN must be a [PAT](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) this is required for the module benc-uk/workflow-dispatch@v1

Added support to activate a workflow systemuser-image

---

.gitignore
SparkMonitor/sparkmonitor/kernelextension.py

Hello.
According to setup.py file of SparkMonitor, minimal supported version of Python is 3.5.
But when I tried to run it on python3.6, an exception has been raised:
```
File "/opt/anaconda2/envs/jh-py36/env/lib64/python3.6/subprocess.py", line 403, in run
with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
`capture_output` argument was added  to python 3.7+ and it does not exist on python 3.6. In this PR I fixed this compatibility issue.
But after fixing it I've received another exception:
```
File "/opt/anaconda2/envs/jh-py36/env/lib64/python3.6/site-packages/sparkmonitor/kernelextension.py", line 185, in configure
log.info("SparkConf Configured, Starting to listen on port:", str(port))
Message: 'SparkConf …
```

Fix python3.6 compatibility

---

.github/workflows/swan-ci-ca.yml

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Fix deprecated command set-env in Github Actions

---

SparkConnector/sparkconnector/configuration.py

Spark on K8S version 2.4 does not support --packages (confing parameter spark.jars.packages).
The Spark connector in SWAN throws an error, signaling this.
Spark 3.x supports the use of spark.jars.packages (in client mode).
As we have now moved to Spark 3.0.1 in LCG 99 and Spark 3.1.1 in future LCG 100, this updates the SWAN connector removing the check so that we can use the new functionality.

[ITHADOOP-1024] Remove check on spark.jars.packages for Spark on K8S

---

SparkConnector/sparkconnector/configuration.py

This PR moves the options in the Spark3Shuffle bundle, to be hardcoded on the connector for Spark 3 running on K8s (cloud containers cluster). (These options need to be set always for Spark3 on K8s for dynamic resource allocation to work without an external shuffle service)
Ideally this config could live near `gitlab/db/hadoop-confext/conf/etc/analytix/spark3.analytix/spark-defaults.conf`, but these options are specific to Spark on K8s only.

ITHADOOP-1020: Configure shuffle for Spark 3.x on K8s

---

SwanContents/swancontents/templates/page.html

Fixes #144
Unlike what I say in the ticket, I just did a small fix without going into wether this is a named server setup or not.

SwanContents: fix change config url for deployments with different base path

---

SparkConnector/sparkconnector/configuration.py

- This is no longer required, as it is part of the spark distribuition and not needed in our cluster
- This is also causing problems when EOS has an I/O error for that path

Remove hadoop-mapreduce-client-core-2.6.0-cdh5.7.6.jar

---

SwanContents/setup.py
SwanContents/swancontents/filemanager/checkpoints.py
SwanContents/swancontents/filemanager/swanfilemanager.py
SwanContents/swancontents/templates/tree.html
SwanShare/src/extension.js

* Workaround for checkpoints failure preventing opening notebooks via JupyterLab
* Update to latest upstream (6.4.0)
*  Fixes to bugs introduced in #92:
* impossibility to share in the notebook editor (#124)
* creating un-named projects just creates a folder and not a project (#194)
Fix #124
Fix #194

Fixes to swancontents

---

HdfsBrowser/hdfsbrowser/serverextension.py

Some times we don't want to validate the SSL certificates of name nodes.
Added an extra configuration to ignore ssl validation

add config validate_cert 

---

SparkConnector/setup.py
SparkConnector/sparkconnector/__init__.py
SparkConnector/sparkconnector/connector.py
SwanPortAllocator/.bumpversion.cfg
SwanPortAllocator/MANIFEST.in
SwanPortAllocator/README.md
SwanPortAllocator/jupyter-config/jupyter_notebook_config.d/swanportallocator.json
SwanPortAllocator/jupyter-config/jupyter_server_config.d/swanportallocator.json
SwanPortAllocator/pyproject.toml
SwanPortAllocator/setup.py
SwanPortAllocator/swanportallocator/__init__.py
SwanPortAllocator/swanportallocator/_version.py
SwanPortAllocator/swanportallocator/portallocator.py

Even though `SparkConnector` is the only SWAN component that needs to allocate ports at the moment, the future support for Dask HTCondor and its need for port allocation motivates the separation of `PortAllocator` in its own extension, which will centrally manage ports for any SWAN component that needs them.

Separate PortAllocator from SparkConnector

---

SparkConnector/MANIFEST.in

add yarn.lock to MANIFEST.in so that `python -m build` from an isolated venv works.

Fix CI for SparkConnector

---

.flake8
.gitignore
.pre-commit-config.yaml
README.md
SwanDask/.bumpversion.cfg
SwanDask/MANIFEST.in
SwanDask/README.md
SwanDask/jupyter-config/jupyter_notebook_config.d/dask_labextension.json
SwanDask/jupyter-config/jupyter_server_config.d/dask_labextension.json
SwanDask/pyproject.toml
SwanDask/setup.py
SwanDask/swandask/__init__.py
SwanDask/swandask/__main__.py
SwanDask/swandask/_version.py
SwanDask/swandask/app.py

This simple wrapper allows us to run Dask not as a server extension, but as a separate process where we can configure the environment. I don't think we can get simpler, and less maintenance free, than this.
For now, the environment is taken from the python3 kernel (this could be configurable at some point). 
**I haven't tested it with the LCG stack, so we might need to fix some details** (add some local path in the env, if we serve the dask extension locally, or maybe change the way we call the process, since the current approach will probably use the local python binary instead of the lcg). But these are very minor issues.
This extension requires a to-be-released version of `jupyter-server-proxy`. The latest doesn't allow empty bodies on PUT requests, which the Dask extension does when …

SwanDask: wrapper to dask-labextension

---

SwanPortAllocator/swanportallocator/portallocator.py

Before, if SPARK_PORTS was not defined, an empty string was added
to the list of available ports.

Portallocator - Fix case when SPARK_PORTS is not defined

---

SparkConnector/nbextension/src/extension.js
SparkConnector/nbextension/src/templates/connected.html
SparkConnector/src/components/connected.tsx

Fix broken links to spark context and spark session description + propose minor change to the description of the WebUI and Spark Metrics Dashboard links

[SPARK-8] fix broken links and update descriptions in the window "Spark clusters connection

---

SparkConnector/sparkconnector/configuration.py

Disable console progress as it would be printed in the notebook as of ipython 6 for Spark on K8S.
This configuration is already there for Spark on YARN/HADOOP.

Disable console progress for Spark on K8S

---

SparkConnector/nbextension/src/extension.js
SparkConnector/sparkconnector/configuration.py
SparkConnector/src/components/connected.tsx
SparkConnector/src/labconnector.ts
SparkConnector/src/store.ts

The use of the Spark history server was a workaround introduced for SWAN on k8s, this appears not to be necessary any more, the WebUI should be preferred as it has more functionality.

Use the WebUI for Spark on YARN instead of using Spark history server.

---

SwanContents/swancontents/filemanager/swanfilemanager.py

Set a 2 minutes timeout when cloning git repositories through the SWAN file manager.
Furthermore, added a double dash to the git clone process, to prevent security issues (users can pass command options in the place of the url currently).

Refactor git clone for git projects on SWAN

---

SparkConnector/sparkconnector/configuration.py

orgId should not be hardcoded for the spark metrics dashboard. The  goes together with an update of the parameters bundle used to migrate the dashboard to a new location.

orgId should not be hardcoded for the spark metrics dashboard

---

SwanContents/MANIFEST.in
SwanContents/swancontents/__init__.py

By mistake I forgot to change the api endpoint, so there were some warning about future deprecation.
The wheel was also missing the static files.
I'll also add a Lab extension to allow users to switch between interfaces (lab/old), just like what happens when Lab is installed with the new Notebook (v7) and Nbclassic.

Fix swancontents

---

SwanDask/swandask/__init__.py

SwanDask (and Dask lab extension) make use of libraries that are present in the LCG release (e.g. Dask), that is why we configure the SwanDask environment with the LCG release. In addition, here we make sure the Python of the LCG release is used, and not the one installed in the base user image, since this can cause compatibility problems.

Make sure SwanDask runs with the LCG python

---

SwanDask/swandask/app.py

Since jupyter_server_proxy 3.0.0, host_whitelist is replaced by host_allowlist:
https://jupyter-server-proxy.readthedocs.io/en/latest/changelog.html#id46

Adapt to new naming host_allowlist in jupyter_server_proxy

---

SwanPortAllocator/swanportallocator/portallocator.py

This changes the port allocator to:
- Handle a variable with generic computing ports, which can be requested by either the Spark connector or the Dask lab extension.
- If a process already asked for ports, do not return the same ports if the same process asks again -- this is important for the Dask lab extension to work, because on every creation of a SwanHTCondorCluster, a new port will be requested by the same process
- Be able to release ports (when a SwanHTCondorCluster is shut down, its corresponding port is released).

Make portallocator generic to also handle requests from the Dask lab extension

---

SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html

A new parameter is added to the SwanCustomEnvironments extension in order to automatically open a file after the session is launched and the environment is created.
The file path can be relative to CERNBOX_HOME or Git Repo.

swancustomenvironments: New session args feature with new `file` parameter

---

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh
SwanCustomEnvironments/swancustomenvironments/serverextension.py

- Default for args is an empty string instead of `None`. This is done because bash scripts interpreter `None` as a normal string. Empty strings are the proper way to inform the system the variables are empty.
- Allow the git url pattern to accept `.git` extension
- Comments' explanation simplified
- Redirecting output also when creating the environments and symlinking the kernels (useful in case of errors)

swancustomenvironments: change defaults, comments, and loggings

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/mamba.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh
SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh
SwanCustomEnvironments/swancustomenvironments/serverextension.py
SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html

Conda (mamba) environments can now be built passing the argument `--conda` into `makenv.sh` script. Some logic and code flow modifications were needed in order to build them sameway as `python-venv`.

swancustomenvironments: New conda environment option

---

SwanShare/src/api.js

Now it's enforced and returns 403 if this header is not provided.

swanshare: talk to backend with X-XSRFToken

---

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh

The swan image already configures the skeleton of a Python3 kernel. When selecting an LCG release, such skeleton is filled with the environment coming from that LCG release.
What we do here is reuse the same skeleton too, but this time, for custom environments, we override the kernel.json of the skeleton with that of the environment.
If instead we create another directory inside kernels with the environment kernel, two Python kernels show up, which is not what we want.

[SwanCustomEnvs] Prevent two Python kernels from appearing

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/mamba.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh
SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html

- Insert line breaks between lines instead of chunks (some lines can be empty).
- Fix mistyped variables name from `LOG_PATH` to `LOG_FILE`

swancustomenvironments: Fix line breaks in output and piping to log file

---

SwanContents/swancontents/serverextension/templates/download.html

This is required after the update to hub v4.1.6

[SwanContents] Make download feature set xsrf auth header

---

SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh

`_log` is not defined yet. As we don't need to store these definitions in the log file, we can go with `echo`

swancustomenvs: Use `echo` instead of `_log`

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/mamba.sh

This is needed due to the installation of the kernel. It needs to be poiting to the exact python binary. Otherwise, it will use the base python.

swancustomenvironments: Activate mamba

---

SparkConnector/setup.py
SparkConnector/sparkconnector/configuration.py
SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh
SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh

Customenv sessions don't have the same configuration as LCG software stack. Which leads to the lost of the spark defaults provided by NXCals. This specially affetcs extraJavaOptions, since its default is being overwritten by SparkConnector, but necessary to preserve, once it contains the list of NXCals instances for running jobs on.

sparkconnector: Preserve the default value of `extraJavaOptions`

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh
SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh
SwanCustomEnvironments/swancustomenvironments/serverextension.py
SwanCustomEnvironments/swancustomenvironments/templates/customenvs.html

Changes on the way repository was manage due to its previous type flexibility. Now only git repos are taking into account.
Pipe stderr to stdout in order to also write the error messages in the log file

swancustomenvironments: Remove `repo_type`

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh

SparkConnector cannot be updated by now. Installing it by git repo takes much longer. So we install `swanportallocator` separately and  the current SparkConnector package with its dependencies longside

swancustomenvironments: Implementation of sparkconnector bypass

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh

Create a `swan` environment for installing SparkConnector and SparkMonitor, in order to avoid their presence among the other user packages in the created environment by the user.
Afterwards, create a `.pth` file among the user packages for adding these Spark packages to the user context.
This way, when user `pip freeze` his environment, it won't contain Spark packages, keeping its integrity. A `--local` flag needs to be passed in order to preserve its scope restricted, ignoring Spark extensions.

swancustomenvironments: Create a middle layer environment

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh
SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh

When creating a custom environment, two types of a requirements file
can now be provided:
1. High-level requirements, i.e. not fully resolved. These are provided by
a file called requirements.in.
2. Fully resolved requirements, i.e. all the necessary packages including
their dependencies and specific versions. These are provided by a file
called requirements.txt.
If (2) is present, the packages will be installed with uv for performance
reasons. Since a full resolution has already been done, it is safe to do
so (we don't depend on the resolution of uv). If (2) is not present but
(1) is, the packages will be installed with pip, probably in a slower way
but with the dependency resolution of pip. This guarantees a more
stable solution in the medium-long term.

swancustomenvironments: Install requirements using `uv`

---

SwanCustomEnvironments/swancustomenvironments/scripts/builders/accpy.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/mamba.sh
SwanCustomEnvironments/swancustomenvironments/scripts/builders/venv.sh
SwanCustomEnvironments/swancustomenvironments/scripts/makenv.sh

Due to the fact `venv-pack` (used by nxcals) doesn't support editable packages to be shipped with the environment, and the swan middle layer was based on the use of a .pth file, which is seen as a source of editable packages and therefore makes venv-pack fail. For this reason, the swan middle layer has been removed and the extra packages have been added directly to the environment. In spite of this, the requirements file must not be modified.

swancustomenvironments: Remove swan middle layer

---

SparkConnector/sparkconnector/configuration.py

Fetch the major and minor versions of python properly, instead of just getting the first 3 digits, since now there is python 3.10 and 3.11

sparkconnector: Fetch python major and minor versions correctly

---

SparkConnector/sparkconnector/configuration.py

- Customenv sessions do not have the same configuration as the LCG software stack. This leads to the loss of the Spark defaults provided by NXCals. This especially affects extraJavaOptions, since its default is being replaced by SparkConnector, but it is necessary to preserve it since it contains the list of NXCals instances to run the jobs.
- With `SPARK_DRIVER_EXTRA_JAVA_OPTIONS` defined as environment variable in the kernel, it configures `extraJavaOptions` with the default spark configuration.
- User options take now precedence over the default ones

sparkconnector: Prevention for SwanCustomEnvironments

---

SwanContents/swancontents/checkpoints/eoscheckpoints.py
SwanContents/swancontents/filemanager/eos/fileio.py
SwanContents/swancontents/filemanager/projects_mixin.py
SwanContents/swancontents/filemanager/swan_eos_filemanager.py

Use an async file contents manager to have async file operations, such as for listing and saving files. This was implemented to solve an issue that was being caused by users not being able to type in terminal when they would open a folder with a large amount of files in the file browser of JupyterLab
By separating the file operations in different threads and releasing control of the main one, the issue has been fixed

swancontents: Use async file contents manager

---

SparkConnector/sparkconnector/configuration.py

This is to enable TLS communication between the Hadoop nodes and SWAN

sparkconnector: Change Spark weburls to use HTTPS

---

SparkConnector/sparkconnector/configuration.py

This is to update the container image used by Spark on k8s to the latest version of Alma9 as of 20250522.

Update image used by Spark on K8S

---

SwanContents/swancontents/serverextension/templates/download.html

Get `use-jupyterlab` checkbox value that is sent from `SwanSpawner`, in order to differentiate between ClassicUI and JupyterLab

swancontents: Open projects also on JupyterLab
